premiosplatziapp/polls/urls.py
from django.urls import path
from . import views


app_name="pollss"

urlpatterns=[
    # ex:/polls/
    path("", views.IndexView.as_view(),name="index"),
    # ex:/polls/5/
    path("<int:pk>/detail", views.DetailView.as_view(),name="detail"),
    # ex:/polls/5/results
    path("<int:pk>/results/", views.ResultView.as_view(),name="results"),
    # ex:/polls/5/vote
    path("<int:question_idd>/vote", views.vote,name="vote"),
]

premiosplatziapp/premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/",include("polls.urls"))
]

premiosplatziapp/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.


class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >=timezone.now() - datetime.timedelta(days=1)
    
    
class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

premiosplatziapp/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


# def index(request):
#    latest_question_list=Question.objects.all()
#    return render(request,"polls/index.html",{
#        "latest_question_list":latest_question_list})

# def detail(request, question_idd):
#    question=get_object_or_404(Question,pk=question_idd)
#    return render(request,"polls/detail.html",{
#        "question":question
#    })

# def results(request, question_idd):
#    question=get_object_or_404(Question,pk=question_idd)
#    return render(request,"polls/results.html",{
#        "question":question
#    })

class IndexView(generic.ListView):
    template_name="polls/index.html"
    context_object_name="latest_question_list"
    def get_queryset(self) :
        """Return the last five published questions"""
        return  Question.objects.order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    model=Question
    template_name="polls/detail.html"
    
class ResultView(generic.DetailView):
    model=Question
    template_name="polls/results.html"



def vote(request, question_idd):
    question=get_object_or_404(Question,pk=question_idd)
    try:
        selected_choice=question.choice_set.get(pk=request.POST["choice"])
    except (KeyError,Choice.DoesNotExist):
        return render(request,"polls/detail.html",{
            "question":question,
            "error_message":"No elegiste una respuesta"
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse("pollss:results", args=(question.id,)))

premiosplatziapp/polls/templates/polls/detail.html
<form action="{% url "pollss:vote" question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{question.question_text}}</h1></legend>
    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input  type="radio"
                name="choice"
                id="choice{{forloop.counter}}"
                value="{{choice.id}}"
        >
        <label for="choice{{forloop.counter}}">
            {{choice.choice_text}}
        </label>
        <br>

    {% endfor %}
</fieldset>
<input type="submit" value="Votar">
</form>


<!-- 

<h1>{{ question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}}</li>
    {% endfor %}
    
</ul> 

-->

premiosplatziapp/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url "pollss:detail" question.id %}"> {{question.question_text}}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <p> No polls are available </p>
{% endif %}

premiosplatziapp/polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text}} -- {{choice.votes }} vote{{choice.votes|pluralize}}</li>
{% endfor %}

</ul>

<a href="{% url 'pollss:detail' question.id %}" > Te gustaria votar de nuevo? </a>